packages:
  - reader
  - fs
  - epub
  - transcript
catalog:
  vite: ^5.4.11
  vue: ^3.5.13
  "@vitejs/plugin-vue": ^5.2.1
  typescript: ^5.6.3
  vue-tsc: ^2.1.10
  "@types/wicg-file-system-access": ^2023.10.5
  vite-plugin-qrcode: ^0.2.3
