packages:
  - reader
  - fs
  - epub
  - transcript
catalog:
  vite: ^5.4.3
  vue: ^3.5.3
  "@vitejs/plugin-vue": ^5.1.3
  typescript: ^5.5.4
  vue-tsc: ^2.1.6
  "@types/wicg-file-system-access": ^2023.10.5
  vite-plugin-qrcode: ^0.2.3
