/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    'Mdi:bookOpenBlankVariant': typeof import('~icons/mdi/book-open-blank-variant')['default']
    MdiArrow: typeof import('~icons/mdi/arrow')['default']
    MdiBaselineList: typeof import('~icons/mdi/baseline-list')['default']
    MdiBook: typeof import('~icons/mdi/book')['default']
    MdiBookmark: typeof import('~icons/mdi/bookmark')['default']
    MdiCaret: typeof import('~icons/mdi/caret')['default']
    MdiCaretDown: typeof import('~icons/mdi/caret-down')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiExpand: typeof import('~icons/mdi/expand')['default']
    MdiExpandDown: typeof import('~icons/mdi/expand-down')['default']
    MdiExpandLess: typeof import('~icons/mdi/expand-less')['default']
    MdiExpandMore: typeof import('~icons/mdi/expand-more')['default']
    MdiFolder: typeof import('~icons/mdi/folder')['default']
    MdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiKeyboardArrowRight: typeof import('~icons/mdi/keyboard-arrow-right')['default']
    MdiReload: typeof import('~icons/mdi/reload')['default']
    MdiUpload: typeof import('~icons/mdi/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
