/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Mdi:bookmark': typeof import('~icons/mdi/bookmark')['default']
    'Mdi:bookOpenBlankVariant': typeof import('~icons/mdi/book-open-blank-variant')['default']
    'Mdi:close': typeof import('~icons/mdi/close')['default']
    'Mdi:contentCopy': typeof import('~icons/mdi/content-copy')['default']
    'Mdi:trashCan': typeof import('~icons/mdi/trash-can')['default']
    'Mdi:volume': typeof import('~icons/mdi/volume')['default']
    MdiBook: typeof import('~icons/mdi/book')['default']
    MdiBookmark: typeof import('~icons/mdi/bookmark')['default']
    MdiCaret: typeof import('~icons/mdi/caret')['default']
    MdiCog: typeof import('~icons/mdi/cog')['default']
    MdiFolder: typeof import('~icons/mdi/folder')['default']
    MdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    MdiReload: typeof import('~icons/mdi/reload')['default']
    MdiUpload: typeof import('~icons/mdi/upload')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
